### ISSUE TITLE
Double output  when "bashdoc file.sh" while the rest works as intended

### ISSUE THREAD

**Issue by AndiKod** [dustinknopoff/bashdoc#4]
Hi, It's not much but I have a strange result on a command.

Tried with the bare minimum. One file one comment on the main() function, and when calling the -j or -t flags everything is nice and smooth. The -j command even displays the results in the console as I was expecting the main "no params" to do.

Yet, when I call simply bashdoc and the file, -c or not, it outputs:

```shell
Help: bin
main fn - noParams: The content for the Home Route
Help: bin
main fn - noParams: The content for the Home Route
```
...didn't yet looked at the Rust code, but I bet it's not the expected outcome.

**Comment by dustinknopoff** [comment]
Let me know if this fixed the issue for you. I'm glad code from 6 years ago was easy enough to resolve this :)

**Comment by AndiKod** [comment]
Impressed too. I sometime struggle to get my head around on code from last month, that's why I'm taking "docs generation" resolution in advance before the new year.

The fix worked, installed via Cargo. Thanks a lot. 

I will eventually include bashdoc in a project I have around creating and managing bash scripts, as docs are important and I like the concise syntax.
